In [1]:
import numpy as np

scalar = np.array(10)
print(scalar)

10


In [2]:
vector = np.array([10,20,30])
print(vector)

[10 20 30]


In [3]:
matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [4]:
tensor = np.array([
[[1,2],[3,4]],
[[5,6],[7,8]]
])

print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
